language: c
compiler: gcc
sudo: required
install:
  - sudo apt-get -qq update
  - sudo apt-get install -y openjdk-7-jdk rpm libc6-dbg
  - wget https://launchpad.net/ubuntu/+source/valgrind/1:3.12.0-1ubuntu1/+build/11192226/+files/valgrind_3.12.0-1ubuntu1_amd64.deb
  - wget https://launchpad.net/ubuntu/+source/shellcheck/0.4.4-4/+build/11197881/+files/shellcheck_0.4.4-4_amd64.deb
  - sudo dpkg -i *.deb
  - pushd samples
  - sudo cp -Rv etc usr /
  - cd dpkg
  - sudo cp -Rv etc /
  - popd
script:
  - cmake -D CMAKE_BUILD_TYPE=Debug -D BUILD_DOC=ON ./
  - make package
  - make jem-test
  - sudo dpkg -i dist/jem-0.1-1.x86_64.deb
  - shellcheck usr/bin/run-java-tool.bash
  - shellcheck tests/run-tests.sh
  - sudo ./tests/run-tests.sh -j
notifications:
  email: false
deploy:
  provider: releases
  api_key:
    secure: CLBKURe0w+Gtr2AcNwn2/17+jc5QwFZCD2C/HaHqgAmoBsC3FpedDRUUH90skCTfNpu6O/xfS2Unoijd56zwNUtZpPcfxeJOaWqYxVrxNTsp8YYV9IDoG+x8EF1Cmp4SZa2vW+X72Y8FqzjzN8PVJJawLLQEWawF5hg87gBf24mGl8ow1Xq3jGnInsOz0mMU3hbtztZCrh3TU3rSv3Wcrbu4ZROdd5EdhCrd2NIv0QmkaL+/Uhv78m0fne5DdLlEGKBnhdToGZc93csCzxGQPg6fgSYyJO9t5372yeK+dY0Z0f20ciWoFutN7qB7MTapFw8MyM/trEz5ab/gaHJUQ9Dh/ctAXH9cRrCTQHVSF65eqMxu3rTLa8YTbwFObC2BsEOSOt7NXW+mk7M8AV/f89ywwnj1tOkPWlkmgAOudG776ar/wHTbDfJGr1Xbou0IVm5laYd4hnlgq+HIeT0Z+b9xtXFGxwiQcAS11ACQUpS8VZcNHP2FzfgpIlhWBi7kIqelwXT/rG9dKzukQlAgelXUDC0Jcf2TgmNO4yAtz5JKBVoCbiHfLywYgXg7YI2JJRQXKIn43BzxBBa2tCn83kuWnYdqveBdhWtjqz5bhfryCcFuDQOj43ogkLOxNx3MGaw1uVlUw+e0bqllNXOhQGyxlQNzby6a9QYNi1FX8Dk=
  file:
    - dist/jem-0.1-1.x86_64.deb
    - dist/jem-0.1-1.x86_64.rpm
  on:
    repo: Obsidian-StudiosInc/jem
    tags: true
