language: c
compiler: gcc
sudo: required
install:
  - sudo apt-get update
  - sudo apt-get install -y openjdk-7-jdk rpm valgrind
  - pushd samples
  - sudo cp -Rv usr /
  - cd dpkg
  - sudo cp -Rv etc /
  - popd
script:
  - cmake -D CMAKE_BUILD_TYPE=Debug -D BUILD_DOC=ON ./ 
  - make package
  - sudo dpkg -i dist/jem-0.1-1.x86_64.deb
  - make jem-test
  - sudo ./tests/run-tests.sh -j
notifications:
  email: false

