language: c
compiler: gcc
sudo: required
install:
  - sudo apt-get update
  - sudo apt-get install -y openjdk-8-jdk valgrind
script: 
  - dpkg-query -L openjdk-8-jdk
  - cmake -D CMAKE_BUILD_TYPE=Debug -D BUILD_DOC=ON ./ 
  - make
#  - make jem-test
